version: '3.9'

services:

  app:
    container_name: cb_rf_api
    image: app:latest
    stop_signal: SIGINT
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    restart: always

    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
